config/routes.rb
Rails.application.routes.draw do
  
  get 'users/rsvp/:user_id' => 'users#forward_user'
  get 'users/rsvp/' => 'users#rsvp'
  post 'users/rsvp' => 'users#rsvp_save'
  get 'users/send_invites' => 'users#send_invites'
  post 'users/send_invites' => 'users#send_invites'
  get 'about' => 'welcome#about'

  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base

  def full_name
    "#{first_name} #{last_name}"
  end

  def send_invite
    UserMailer.invite_email(self).deliver_later
    self.invite_sent = true
    self.save!
  end

  def self.send_invites
    users = User.where(:invite_sent => nil)
    users.each do |user|
      user.send_invite
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
end

def create
	@user = User.new()
end

def show
  @users = User.all.order(:last_name)
end

def forward_user
  user_id = session[:current_user_id] = params[:user_id]
  User.increment_counter :clicked_invite, user_id
  redirect_to action:'rsvp'
end

def rsvp
  logger.debug "Current session user: #{session[:current_user_id]}"
  @user = User.find_by_id(session[:current_user_id])
end

def rsvp_save
  params[:response]
  logger.debug "Person attributes hash: #{params[:response]}"
  user = User.find_by_id(session[:current_user_id])
  if params[:response] == 'attending'
    user.rsvp = true
  else
    user.rsvp = false
  end
  user.save!
  redirect_to controller:'welcome', action:'index'
end

def send_invites
  if request.get?
  else
    User.send_invites
  end
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teknobarn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'about' if params[:action] == 'about' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/rsvp.html.erb
<div id='header'>
  <%= image_tag 'teknobarn_one_line.png' %>
  <br>
  Aug 21-23, 2015
  <br>
  Leesport, PA
</div>
<div id='rsvp'>
<%= form_tag  do %>
  <div>
  RSVP for <span class='orange'><%= @user.full_name%></span>
  <br>
	<%= radio_button_tag(:response, "attending",@user.rsvp) %>
  <label for="response_attending"><span></span>I will be attending Teknobarn 2015</label>
	<br>
	<%= radio_button_tag(:response, "not_attending") %>
	<label for="response_not_attending"><span></span>I will not be attending</label>
  </div>
  <div id='about_link'>
    <%= link_to 'About Teknobarn', about_path %>
  </div>
  <div id="details" class="center">
  <br>
  PLEASE READ
  <br>
  Welcome to the madness!  You're one step away from the best weekend of the year.
  <br>
  After hitting the submit button below, please remit payment via Venmo to Andrew Weist (@aweist) in the amount of $85.  
  A bunch of really smart people got together in a room for a weekend and figured out that is what it's going to cost to put on this year's spectacle.
  If Venmo absolutely isn't an option for you, please let him know (andrew.weist@gmail.com), and you can arrange an alternative form of payment.
  <br>
  <br>
  This year will be <b><u>tent camping only</u></b> due to the anticipated number of attendies not being able to fit in the Weist household.  Please let Andy know if you have any serious issues with camping (allergies, etc.), or will have difficulty procuring a tent to use.  We'll have plenty of tent space as long as we plan ahead.
  <br>
  <br>
  Now hit submit and let the countdown begin
  </div>
  <br>
  <div class="submit_rsvp center">
    <%= submit_tag "Submit"%>
  </div>
<% end %>
</div>
<br>
<br>

app/views/users/send_invites.html.erb
<%= form_tag  do %>
  <%= submit_tag "Submit"%>
<% end %>

app/views/users/show.html.erb
<h1>All users</h1>

<table class="users" cellspacing=0 cellpadding = 0>
  <tr>
    <th>
    </th>
    <th>
      ID
    </th>
    <th>
      Name
    </th>
    <th>
      Email
    </th>
    <th>
      RSVP
    </th>
    <th>
      Clicked
    </th>
  </tr>
  <% @users.each_with_index do |user, index| %>
    <tr>
      <td>
        <%= index+1%>
      </td>
      <td>
        <%= user.id %>
      </td>
      <td>
        <%= user.full_name %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= user.rsvp %>
      </td>
      <td>
        <%= user.clicked_invite %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= @users.where(:rsvp => true).count %></td>
  </tr>
</table>

app/views/welcome/about.html.erb
<%= image_tag 'teknobarn_one_line.png' %>
<h1>Friday, Aug 21st - Sunday, Aug 23rd</h1>
<br>
<h1>Teknobarn is located at:
<br>
135 Gernants Church Rd
<br>
Leesport, PA 19533
</h1>
<br>

<h2>
Events include (but are not limited to):
<ul>
  <li>Civil War pong in a Civil War-era barn</li>
  <li>Drunk tubing down the Schuylkill River</li>
  <li>Quoits tournament</li>
  <li>Giant Slip 'n' Flip</li>
  <li>Bonfire</li>
  <li>Fireworks</li>
  <li>BBQ-ing various species of animals</li>
  <li>Volleyball</li>
  <li>Pong Tournamnet</li>
  <li>Goats</li>
  <li>General debauchery</li>
</ul>
</h2>

<h2 id='description'>
Teknobarn is THE premiere food/alcohol/music festival in Leesport, PA.  Ok perhaps it's not quite a 'festival' yet... but we're getting there!  Join an all star cast of partiers for a madness-filled weekend in the farmlands of Pennsylvania.  Experience the Year of the Goat like it's meant to be... with an all-you-can-eat, all-you-can-drink, no holds barred adventure where your only concern will be not getting lost in the corn field.  If you're not persuaded by the above list, ask someone who has been there before, it is truly a magical place.  And don't worry, the cows are long gone, so you don't have to worry about being run over by stampeding cattle... and yes, we have electricity and indoor plumbing and (gasp!) even wifi.  
<br>
<br>
Think you can hang?  Check out the pics below and sign up from your invite!
</h2>
<blockquote class="imgur-embed-pub" lang="en" data-id="a/hGigH"><a href="//imgur.com/a/hGigH">Teknobarn 2k14</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

app/views/welcome/index.html.erb
<div id='background'
	data-3000='top:0%;opacity:1'
	data-5000='opacity:0'>
</div>
<div id='yearofthegoat' 
	data-129='display:none' 
	data-130='display:block;top:195px'
	data-700='opacity:0'
	data-800='opacity:1'
	data-1200='opacity:1'
	data-1400='opacity:0'>
	<span class='redish'>#</span><span class='blueish'>yearofthegoat</span>
</div>
<div id='logo' 
	data-0='top:0px' 
	data-130='top:-130px;opacity:1' 
	data-800='opacity:0'>
	<%= image_tag 'teknobarn_one_line.png' %>
	<br>
	<%= image_tag 'goat_mixed.png' %>
</div>
<div id='events'
	data-1400='opacity:0'
	data-1700='opacity:1'
	data-2400='top:0%'
	data-3000='top:-100%'>
	<span id='date' class='blueish'>8<span class='redish'>&middot</span>21<span class='redish'>&middot</span>15</span>
	<div id='events-list' class='redish'
		data-1900='opacity:0'
		data-2100='opacity:1'>
		Fireworks <span class='blueish'>&middot</span> Civil War Pong <span class='blueish'>&middot</span> Bonfire 
		<br>
		Tubing <span class='blueish'>&middot</span> Slip 'n' Flip <span class='blueish'>&middot</span> BBQ
		<br>
		Goats <span class='blueish'>&middot</span> Quoits <span class='blueish'>&middot</span> Jello Shots
		<br>
		Slap Cup <span class='blueish'>&middot</span> Ahoy <span class='blueish'>&middot</span> Ming
		<br>
		Battleship <span class='blueish'>&middot</span> Santa <span class='blueish'>&middot</span> Camping
		<br>
		Rage
	</div>
</div>
<div class='hero'
	data-5000='opacity:0'
	data-5500='opacity:1;top:50px'
	data-7000='opacity:0'>
	<%= image_tag 'pong3.gif' %>
</div>
<div class='hero'
	data-6500='opacity:0'
	data-7000='opacity:1;top:50px'
	data-8000='opacity:0'>
	<%= image_tag 'group.jpg' %>
</div>

<% (1..7).each do |i| %>
	<div class='hero'
		data-<%=6500+(1500*i)%>='opacity:0'
		data-<%=7000+(1500*i)%>='opacity:1;top:50px'
		data-<%=8000+(1500*i)%>='opacity:0'>
		<%= image_tag "hero_#{i}.jpg" %>
	</div>
<%end %>

<div class='hero'
	data-<%=6500+(1500*8)%>='opacity:0'
	data-<%=7000+(1500*8)%>='opacity:1;top:50px'>
	<%= image_tag "hero_8.jpg" %>
</div>

<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/skrollr/0.6.30/skrollr.min.js" %>